"""Initial migration.

Revision ID: d19dd2c3e751
Revises: 
Create Date: 2024-07-09 18:29:09.592453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19dd2c3e751'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('response', sa.String(length=1000), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('question3')
        batch_op.drop_column('question2')
        batch_op.drop_column('question1')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_completed_questionnaire', sa.Boolean(), nullable=True))

    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('weight_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date')

    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_completed_questionnaire')

    with op.batch_alter_table('questionnaire_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question1', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('question2', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('question3', sa.VARCHAR(length=200), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('response')
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
